### PR TITLE
remove padding from top and sides, so it doesn't disturb baseline grid

### PR DESCRIPTION
**Pull request by lyubomir-popov**
Adding a 4px offset throws things off the baseline grid, so I've changed that to 8 at the bottom, 0 everywhere else.

### CODE REVIEW

**Review by anthonydillon — CHANGES_REQUESTED** [review]
Some patterns are tight to the top of the example and so you can't see the border or shadow at the top

**Comment by lyubomir-popov** [comment]
I've adjusted the values to match  the baseline grid.

**Comment by lyubomir-popov** [comment]
this is ready for another look

**Review by sowasred2012 — APPROVED** [review]
LGTM

**Pull request merged**
